Product Visualization and Management
Riwi-Meta/LOCAL_STORAGE_BACKEND pull request #116
Opened 2024-07-16 15:00 UTC by cristianbyte

### Enhance Product Visualization and Management 

This pull request addresses the user stories related to enhancing product visualization and inventory management in the store application. It introduces features to display product categories and locations, as well as functionalities to identify demanded products and manage low stock items efficiently.

**Changes Implemented:**

1. For Viewing Product Categories and Locations:
    -   Implemented a feature to display the categories and exact locations of all products.
    -   Added filtering options by product category to facilitate product search and browsing.
    -   Enabled functionality for easy updates to product locations through an intuitive interface.
 2. For Identifying Demanded Products and Low Stock Items:
      - A list of best-selling products based on sales data.
      - Products with low stock levels and alerts for those nearing their expiration date.
      - Configuration options for setting low stock thresholds to trigger proactive alerts.

2024-07-17 11:55 UTC, SMoreno73 requested changes
Fix or explan me the reason why you do that in that way

2024-07-17 11:55 UTC, SMoreno73 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/dto/request/update/ProductUpdateLocationResponse.java
Why this response is empty?

2024-07-17 11:55 UTC, SMoreno73 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/dto/response/BestSellingResponse.java
Do you need @ToString?, what do you do?

2024-07-17 11:55 UTC, SMoreno73 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/domain/entities/Product.java
Why do you need @ToString?

2024-07-17 11:55 UTC, SMoreno73 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/infrastructure/mappers/BranchMapper.java
I suggest you put all @Mapping in a agrupation notation -> @Mapppings

2024-07-17 11:55 UTC, SMoreno73 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/infrastructure/services/CustomService.java
Is a good have a pattern, here you forget the final

2024-07-17 13:18 UTC, cristianbyte commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/dto/response/BestSellingResponse.java
It was for testing, I'm going to remove it.

2024-07-24 12:11 UTC, SMoreno73 approved these changes

2024-07-24 12:11 UTC, merged