Feature/ES 16 86a43gm56 Create discount method
Riwi-Meta/LOCAL_STORAGE_BACKEND pull request #118
Opened 2024-07-17 13:24 UTC by mtatiana115

Create discount method

2024-07-17 13:40 UTC, SantiagoProgramador requested changes
Commit the requested changes to merge the branch

2024-07-17 13:40 UTC, SantiagoProgramador commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/controllers/DiscountController.java
> +import com.riwi.localstorage.riwi_local_storage.api.dto.request.create.MembershipRequest;
Unused request of a entity who no belong in the discount controller

2024-07-17 13:40 UTC, SantiagoProgramador commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/controllers/DiscountController.java
> +import com.riwi.localstorage.riwi_local_storage.api.dto.response.MembershipResponse;
delete membership dtos in imports

2024-07-17 13:40 UTC, SantiagoProgramador commented on src/main/java/com/riwi/localstorage/riwi_local_storage/infrastructure/services/DiscountService.java
>    public DiscountResponse create(DiscountRequest request) {
create method is missing the code validation, discount entity should not have repeated code. 
Use validateDiscountRequest method below.

2024-07-18 12:26 UTC, mtatiana115 commented
done

2024-07-18 12:26 UTC, mtatiana115 commented on src/main/java/com/riwi/localstorage/riwi_local_storage/api/controllers/DiscountController.java
> +import com.riwi.localstorage.riwi_local_storage.api.dto.response.MembershipResponse;
done

2024-07-18 13:01 UTC, SantiagoProgramador commented
good job

2024-07-18 13:02 UTC, merged